export const route = {
	landing: "/",
	auth: "/auth",
	signIn: "/auth/sign-in",
	signUp: "/auth/sign-up",
	dashboard: "/dashboard",
	subscription: "/subscriptions",
	product: "/products",
	location: "/locations",
	report: "/reports",
	integration: "/integrations",
	integration_connect: "/integrations/connect",
	workspace: "/workspaces",
	workspace_create: "/workspaces/create",
	workspace_update: "/workspaces/update",
	setting: "/settings",
	setting_certificate: "/settings",
	profile: "/profile",
	video_demo: "https://www.youtube.com/watch?v=35Z_ds3gLwOQ",
	video_tutorial: "https://www.youtube.com/watch?v=2Ja_g3EL2dfF",
	transaction: "/transactions",
	transaction_category: "/transactions/category",
	docs: "/docs",
	pricing: "/pricing",
	developers: "/docs/developers/api",
};
